
import React, { useEffect, useState } from "react";
import './../styles/App.css';

const indianCities = [
  "Mumbai",
  "Delhi",
  "Bangalore",
  "Chennai",
  "Kolkata",
  "Hyderabad",
  "Ahmedabad",
  "Pune",
  "Jaipur",
  "Lucknow",
  "Kanpur",
  "Nagpur",
  "Indore",
  "Thane",
  "Bhopal",
  "Visakhapatnam",
  "Pimpri-Chinchwad",
  "Patna",
  "Vadodara",
  "Ghaziabad",
  "Ludhiana",
  "Agra",
  "Nashik",
  "Faridabad",
  "Meerut",
  "Rajkot",
  "Kalyan-Dombivali",
  "Vasai-Virar",
  "Varanasi",
  "Srinagar",
  "Aurangabad",
  "Dhanbad",
  "Amritsar",
  "Navi Mumbai", 
  "Allahabad",
  "Ranchi",
  "Howrah",
  "Coimbatore",
  "Jabalpur",
  "Gwalior",
  "Vijayawada",
  "Jodhpur",
  "Madurai",
  "Raipur",
  "Chandigarh",
  "Guwahati",
  "Solapur",
  "Hubli-Dharwad",
  "Tiruchirappalli",
  "Bareilly",
  "Moradabad",
  "Mysore",
  "Tiruppur",
  "Gurgaon",
  "Aligarh",
  "Jalandhar",
  "Bhubaneswar",
  "Salem",
  "Warangal",
  "Mira-Bhayandar",
  "Thiruvananthapuram",
  "Bhiwandi",
  "Saharanpur",
  "Guntur",
  "Amravati",
  "Noida",
  "Jamshedpur",
  "Bhilai",
  "Cuttack",
  "Kochi",
  "Udaipur",
  "Bhavnagar",
  "Dehradun",
  "Asansol",
  "Nanded",
  "Ajmer",
  "Jamnagar",
  "Ujjain",
  "Sangli",
  "Loni",
  "Jhansi",
  "Pondicherry",
  "Nellore",
  "Jammu",
  "Belagavi",
  "Raurkela",
  "Mangaluru",
  "Tirunelveli",
  "Malegaon",
  "Gaya",
  "Jalgaon",
  "Udaipur",
  "Maheshtala",
  "Tirupati",
  "Davanagere",
  "Kozhikode",
  "Akola",
  "Kurnool",
  "Bokaro Steel City",
  "Rajahmundry",
  "Ballari",
  "Agartala",
  "Bhagalpur",
  "Latur",
  "Dhule",
  "Korba",
  "Bhilwara",
  "Berhampur",
  "Muzaffarpur",
  "Ahmednagar",
  "Mathura",
  "Kollam",
  "Avadi",
  "Kadapa",
  "Anantapur",
  "Kamarhati",
  "Bilaspur",
  "Shahjahanpur",
  "Satara",
  "Bijapur",
  "Rampur",
  "Shivamogga",
  "Chandrapur",
  "Junagadh",
  "Thrissur",
  "Alwar",
  "Bardhaman",
  "Kulti",
  "Kakinada",
  "Nizamabad",
  "Parbhani",
  "Tumkur",
  "Khammam",
  "Ozhukarai",
  "Bihar Sharif",
  "Panipat",
  "Darbhanga",
  "Bally",
  "Aizawl",
  "Ichalkaranji",
  "Durg",
  "Shillong",
  "Naihati",
  "Kharagpur",
  "Bongaigaon",
  "Hajipur",
  "Deoghar",
  "Madhyamgram",
  "Haldia",
  "Nalgonda",
  "Barasat",
  "Mango",
  "Thanjavur",
  "Bihar Sharif",
  "Morvi",
  "Ongole",
  "Shimla",
  "Nandyal",
  "Parvathipuram",
  "Palghar",
  "Anand",
  "Kolar",
  "Sambalpur",
  "Beawar",
  "Purnia",
  "Baharampur",
  "Suryapet",
  "Miryalaguda",
  "Tanjore",
  "Karimnagar",
  "Rewa",
  "Hosapete",
  "Ambala",
  "Bhimavaram",
  "Giridih",
  "Kumbakonam",
  "Shivpuri",
  "Haridwar",
  "Pudukkottai",
  "Vellore",
  "Machilipatnam",
  "Adoni",
  "Dibrugarh",
  "Chittoor",
  "Veraval",
  "Haldwani",
  "Hosur",
  "Nangloi Jat",
  "Balurghat",
  "Dharmavaram",
  "Kishanganj",
  "Jamalpur",
  "Banda",
  "Gonda",
  "Arrah",
  "Karawal Nagar",
  "North Dumdum",
  "Satna",
  "Unnao",
  "Etah",
  "Lakhimpur",
  "Gangapur",
  "Chinsurah",
  "Hazaribagh",
  "Burhanpur",
  "Raiganj",
  "Panvel",
  "Uluberia",
  "Baranagar",
  "Barasat",
  "Silchar",
  "Hathras",
  "Darjiling",
  "Raniganj",
  "Dibrugarh",
  "Imphal",
  "Agartala",
  "Kohima",
  "Itanagar",
  "Dispur",
  "Aizawl",
  "Gangtok",
  "Shillong",
  "Silvassa",
  "Daman",
  "Kavaratti",
  "Pondicherry",
];

const App = () => {
  const[cities,setCities] = useState();
  const[search,setSearch] = useState("");
  const[click,setClick] = useState(false);

  useEffect(()=>{
    search && setCities(indianCities.filter(city => city.toLowerCase().includes(search.trim().toLowerCase())))
  },[search])

  function updateSearch(city){
    setSearch(city);
    setClick(true);
  }

  return (
    <div>
      <h1>Search cities of India</h1>
      <form>
        <input type="text" placeholder="Search..."
        onChange={(e)=>{
          setSearch(e.target.value)
          setClick(false)
        }}
        value={search}
        />
      </form>

       {
        !click &&
      <ul>
        {
          cities && cities.map((city,index)=>(
            <li key={index} onClick={()=>updateSearch(city)}>{city}</li>
)) }
      </ul>
      }
    </div>
  )
}

export default App
